-- V10: Add amount, discount, and final_amount columns to CATEGORIES table (PostgreSQL)

ALTER TABLE CATEGORIES ADD COLUMN IF NOT EXISTS amount DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE CATEGORIES ADD COLUMN IF NOT EXISTS discount DECIMAL(10,2) NULL DEFAULT 0.00;
ALTER TABLE CATEGORIES ADD COLUMN IF NOT EXISTS final_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00;

UPDATE CATEGORIES SET final_amount = amount WHERE final_amount = 0.00 AND amount > 0;
