-- V9: Create Booking Offers table and add spatial/lifecycle fields

-- 1. Add service area fields to WORKER_PROFILES
ALTER TABLE WORKER_PROFILES ADD COLUMN IF NOT EXISTS service_area_lat DOUBLE PRECISION;
ALTER TABLE WORKER_PROFILES ADD COLUMN IF NOT EXISTS service_area_lng DOUBLE PRECISION;
ALTER TABLE WORKER_PROFILES ADD COLUMN IF NOT EXISTS service_radius_km DOUBLE PRECISION DEFAULT 15.0;

-- 2. Add customer coordinates and lifecycle timestamps to BOOKINGS
ALTER TABLE BOOKINGS ADD COLUMN IF NOT EXISTS customer_lat DOUBLE PRECISION;
ALTER TABLE BOOKINGS ADD COLUMN IF NOT EXISTS customer_lng DOUBLE PRECISION;
ALTER TABLE BOOKINGS ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP;
ALTER TABLE BOOKINGS ADD COLUMN IF NOT EXISTS en_route_at TIMESTAMP;
ALTER TABLE BOOKINGS ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMP;

-- 3. Create BOOKING_OFFERS table
CREATE TABLE IF NOT EXISTS BOOKING_OFFERS (
    id BIGSERIAL PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    worker_id VARCHAR(36) NOT NULL,
    distance_km DOUBLE PRECISION,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    offered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    responded_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_offers_booking FOREIGN KEY (booking_id) REFERENCES BOOKINGS(id) ON DELETE CASCADE,
    CONSTRAINT uq_booking_offers_booking_worker UNIQUE (booking_id, worker_id)
);

CREATE INDEX IF NOT EXISTS idx_booking_offers_worker_status ON BOOKING_OFFERS(worker_id, status);
CREATE INDEX IF NOT EXISTS idx_booking_offers_booking_id ON BOOKING_OFFERS(booking_id);
